config/routes.rb
Rails.application.routes.draw do
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post 'users/sign_in', to: 'users#do_sign_in', as: :do_sign_in
  delete 'users/sign_out', to: 'users#do_sign_out', as: :do_sign_out
  patch 'users/:id/update_password', to: 'users#update_password', as: :update_password
  patch 'users/:id/update_permission', to: 'users#update_permission', as: :update_permission
  resources :users, only: %i[index new create show edit destroy]

  get 'articles/:id/edit_tags', to: 'articles#edit_tags', as: :edit_tags
  post 'articles/:id/edit_tags', to: 'articles#query_tags', as: :query_tags
  patch 'articles/:id/approve', to: 'articles#approve', as: :approve_article
  patch 'articles/:id/hide', to: 'articles#hide', as: :hide_article
  resources :articles

  patch 'tags/:id/add_article', to: 'tags#add_article', as: :add_tag
  delete 'tags/:id/remove_article', to: 'tags#remove_article', as: :remove_tag
  resources :tags

  get 'resources', to: 'resources#index', as: :resources
  post 'resources/upload', to: 'resources#upload'
  get 'resources/:digest', to: 'resources#show', as: :show_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }
  delete 'resources/:digest', to: 'resources#destroy', as: :destroy_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }

  resources :dynamic_routes, path: 'routes', only: %i[index create destroy]
  get 'routes/blackholes/syslog', to: 'blackholes#syslog', as: :syslog
  get 'routes/blackholes/systop', to: 'blackholes#systop', as: :systop
  resources :blackholes, path: 'routes/blackholes', only: %i[index create destroy]

  constraints ->(req) { req.session[:user_id] == 1 } do
    mount RVT::Engine, at: '/routes/blackholes/sysshell'
  end

  get '(*path)', to: 'dynamic_routes#display', defaults: { path: '' }
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 15 }

  belongs_to :author, class_name: 'User', foreign_key: :user_id
  belongs_to :approver, class_name: 'User', foreign_key: :approver_id, optional: true
  has_many :dynamic_routes, dependent: :destroy
  has_and_belongs_to_many :tags

  before_save :render_markdown

  scope :ordered, -> { order(id: :desc) }
  scope :includes_if, ->(really, *what) { really ? includes(*what) : all }
  scope :viewable_by, (lambda do |user|
    if user&.permission? :admin
      all
    elsif user&.permission? :reviewer
      where(hidden: false).or(where(author: user))
    else
      where(hidden: false).where.not(approver: nil).or(where(author: user))
    end
  end)

  # Configure will_paginate default
  self.per_page = 10

  def approved?
    !!approver_id
  end

  def bg_color
    if hidden?
      'bg-hidden'
    elsif !approved?
      'bg-pending'
    else
      ''
    end
  end

  def primary_time
    approved? ? published_at : created_at
  end

  def updated?
    updated_at - primary_time > 5.minutes
  end

  private

  def render_markdown
    renderer = Redcarpet::Render::XHTML.new with_toc_data: true,
                                            prettify: true,
                                            link_attribute: true
    markdown = Redcarpet::Markdown.new renderer,
                                       tables: true,
                                       fenced_code_blocks: true,
                                       autolink: true,
                                       strikethrough: true,
                                       lax_spacing: true,
                                       space_after_header: true,
                                       superscript: true,
                                       underline: true,
                                       highlight: true,
                                       quote: true,
                                       footnotes: true
    recursive = Loofah::Scrubber.new do |node|
      next unless node.name == 'markdown'

      node.name = 'div'
      node.inner_html = markdown.render node.inner_html
    end

    rendered_fragment = Loofah.fragment(markdown.render(body)).scrub!(recursive)
    rendered_fragment.scrub! :strip unless raw?
    self.rendered = rendered_fragment.to_s
    self.summary = rendered_fragment.to_text.truncate(256).split("\n").join(' ')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :ensure_signed_in!, except: %i[index show]
  before_action :ensure_reviewer!, only: :approve
  before_action :ensure_developer!, only: :hide
  before_action :set_article, except: %i[index new create]
  before_action :ensure_edit_permission!, except: %i[index show new create]

  # GET /articles
  def index
    @articles = Article.ordered
                       .viewable_by(this_user)
                       .includes(:tags)
                       .includes_if(this_user&.permission?(:reviewer),
                                    :author,
                                    :approver)
                       .paginate(page: params[:page])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # POST /articles
  def create
    @article = Article.new article_params.merge(author: this_user)
    if @article.save
      flash[:success] = "Created article \"#{@article.title}\"."
      redirect_to @article
    else
      render :new
    end
  end

  # GET /articles/:id
  def show
    no_permission unless this_user!.can_view? @article

    @tags = @article.tags.ordered
  end

  # GET /articles/:id/edit
  def edit; end

  # PATCH /articles/:id
  def update
    if @article.update article_params
      flash[:success] = 'Successfully updated the article.'
      redirect_to @article
    else
      render :edit
    end
  end

  # DELETE /articles/:id
  def destroy
    flash[:dark] = "Deleted article \"#{@article.destroy.title}\"."
    redirect_to articles_path
  end

  # GET /articles/:id/edit_tags
  def edit_tags
    @tags = @article.tags.ordered.paginate page: params[:tags_page]
    @results = Tag.all.paginate page: params[:tags_page]
  end

  # POST /articles/:id/edit_tags
  def query_tags
    @tags = @article.tags.ordered.paginate page: params[:tags_page]
    @results = Tag.where('`name` LIKE ?', "%#{params[:query].gsub(/\s+/, '-')}%")
                  .or(Tag.where('`description` LIKE ?', "%#{params[:query]}%"))
                  .paginate(page: params[:results_page])
    render :edit_tags
  end

  # PATCH /articles/:id/approve
  def approve
    if @article.update approver: this_user, published_at: Time.now
      flash[:success] = "Approved article #{@article.title}."
    else
      flash[:danger] = "Failed to approve the article: #{@article.errors.full_messages.first}."
    end
    redirect_back fallback_location: @article
  end

  # PATCH /articles/:id/hide
  def hide
    if @article.update hidden: params[:hidden]
      flash[:success] = "Article #{@article.title} will be #{@article.hidden? ? 'hidden' : 'listed'} in the index."
    else
      flash[:danger] = "Cannot hide the article: #{@article.errors.full_messages.first}."
    end
    redirect_back fallback_location: @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find params[:id]
  end

  # Call `no_permission' unless this user can edit the article
  def ensure_edit_permission!
    return if this_user.can_edit? @article

    no_permission
  end
end

app/views/articles/_actions.html.erb
<span>
    <% if this_user.permission? :developer %>
        <% if article.hidden? %>
            <%= link_to 'List',hide_article_path(article, hidden: false),
             method: :patch,
             class: 'text-warning' %>
        <% else %>
            <%= link_to 'Hide', hide_article_path(article, hidden: true),
             method: :patch,
             class: 'text-muted' %>
        <% end %> |
    <% end %>
    <% if !article.approved? && this_user.permission?(:reviewer) %>
        <%= link_to 'Approve', approve_article_path(article),
         method: :patch,
         class: 'text-success' %> |
    <% end %>
    <%= link_to 'Edit', edit_article_path(article) %> |
    <%= link_to 'Delete', article,
       method: :delete,
       class: 'text-danger',
       data: { confirm: 'Are you sure?' } %>
</span>

app/views/articles/_entry.html.erb
<div class="alert <%= article.bg_color %>">
    <h3><%= link_to article.title, article, class: 'article-title' %></h3>

    <div class="text-muted">
        <%== article.summary %>
    </div>

    <%= render article.tags, cached: true %>
    <% if this_user&.can_edit? article %>
        <%= link_to 'Edit Tags', edit_tags_path(article) %>
    <% end %>

    <div class="d-flex justify-content-between">
        <span>
            <%= article.primary_time.to_date.inspect %>
            <% if this_user&.permission? :reviewer %>
                &bull; By <%= link_to article.author.username, article.author %>
                <% if article.approved? %>
                    &bull; Approved by
                    <%= link_to article.approver.username, article.approver %>
                <% end %>
            <% end %>
            <% if article.updated? %>
                <br />
                Last update <%= article.updated_at.to_date.inspect %>
            <% end %>
        </span>
        <% if this_user&.can_edit? article %>
            <%= render 'articles/actions', article: article, cached: true %>
        <% end %>
    </div>

    <% if article.summary.blank? %>
        <br />
    <% end %>
</div>

app/views/articles/_form.html.erb
<% content_for :header, javascript_pack_tag('editor', 'data-turbolinks-track': 'reload', nonce: true, defer: true) %>

<% if @article.errors.any? %>
    <div class="alert alert-danger alert-dismissible">
        <h2>Cannot save the article</h2>
        <ul>
            <% @article.errors.full_messages.each do |err| %>
                <li><%= err %></li>
            <% end %>
        </ul>
    </div>
    <%# Suppress bootstrap's error on form %>
    <% @article.errors.clear %>
<% end %>

<p class="text-muted font-italic">
    You can use Markdown and HTML to layout your article. <span>(<a href="/layout_article">?</a>)</span><br />
    To upload an image, directly paste it below or press Ctrl-Alt-u.
</p>
<%= bootstrap_form_with model: @article, local: true do |form| %>
    <div class="input-group">
        <label class="sr-only" for="article_title">Title</label>
        <%= form.text_field :title, wrapper: false, class: 'no-border input-underline text-monospace', label_as_placeholder: true %>
        <div class="input-group-btn">
            <%= form.submit 'Save' %>
        </div>
    </div>
    <%= form.text_area :body, class: 'no-border editor-textarea text-monospace paste-file-upload', hide_label: true %>
<% end %>

<input id="file_upload_tag" type="file" hidden="true" />

app/views/articles/edit.html.erb
<% content_for :title, 'Edit Article' %>
<h1>Edit <%= link_to @article.title, @article %></h1>

<%= render 'form' %>

app/views/articles/edit_tags.html.erb
<% content_for :title, 'Edit Article Tags' %>

<h1>Edit Tags for <%= link_to @article.title, @article %></h1>

<%= bootstrap_form_with url: query_tags_path, layout: :inline, local: true do |form| %>
    <%= form.text_field :query, hide_label: true %>
    <%= form.submit 'Search' %>
    <%= form.button 'Create', class: 'btn btn-success edit-article-tags', formaction: tags_path %>
<% end %>
<br />

<% if @results.any? %>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col"><span class="sr-only">Actions</span></th>
            </tr>
        </thead>
        <tbody>
            <% @results.each do |tag| %>
                <tr>
                    <th scope="row"><%= tag.id %></th>
                    <td><%= render 'tags/tag', tag: tag, cached: true %></td>
                    <td>
                        <% if tag.description.blank? %>
                            <span class="text-muted font-italic">
                                There is no description for this tag... yet!
                            </span>
                        <% else %>
                            <span class="text-secondary">
                                <%= tag.description.truncate(64).gsub(/\n+/, ' ') %>
                            </span>
                        <% end %>
                    </td>
                    <td>
                        <% if @article.tags.include? tag %>
                            <%= link_to 'Remove', remove_tag_path(tag, article_id: @article),
                             method: :delete,
                             class: 'text-danger' %>
                        <% else %>
                            <%= link_to 'Add', add_tag_path(tag, article_id: @article), method: :patch %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p class="text-secondary font-italic">There is no tag... yet!</p>
<% end %>

<%= will_paginate @results, param_name: :results_page %>
<hr />

<h2>Current Tags</h2>
<% if @tags.any? %>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col"><span class="sr-only">Actions</span></th>
            </tr>
        </thead>
        <tbody>
            <% @tags.each do |tag| %>
                <tr>
                    <th scope="row"><%= tag.id %></th>
                    <td><%= render 'tags/tag', tag: tag, cached: true %></td>
                        <td>
                            <% if tag.description.blank? %>
                                <span class="text-muted font-italic">
                                    There is no description for this tag... yet!
                                </span>
                            <% else %>
                                <span class="text-secondary">
                                    <%= tag.description.truncate(64).gsub(/\n+/, ' ') %>
                                </span>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to 'Remove', remove_tag_path(tag, article_id: @article),
                             method: :delete,
                             class: 'text-danger' %>
                        </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%= will_paginate @tags, param_name: :tags_page %>
<% else %>
    <p class="text-secondary font-italic">This article has no tags... yet!</p>
<% end %>

app/views/articles/index.html.erb
<%= render partial: 'entry', collection: @articles, as: :article %>

<% if @articles.any? %>
    <%= will_paginate %>
<% else %>
    <p class="text-secondary font-italic">
        There is no article... yet!
        <% if signed_in? %>
            <%= link_to 'New Article', new_article_path %>
        <% end %>
    </p>
<% end %>

app/views/articles/new.html.erb
<% content_for :title, 'New Article' %>
<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= content_for :title, @article.title %>

<h1 class="<%= @article.bg_color %>">
    <%= link_to @article.title, @article, class: 'article-title' %>
</h1>

<%= render @tags, cached: true %>
<% if this_user&.can_edit? @article %>
    <%= link_to 'Edit Tags', edit_tags_path(@article) %>
<% end %>

<div class="d-flex justify-content-between">
    <span>
        <%= @article.primary_time.to_date.inspect %>
        <% if this_user&.permission? :reviewer %>
            &bull; By <%= link_to @article.author.username, @article.author %>
            <% if @article.approved? %>
                &bull; Approved by
                <%= link_to @article.approver.username, @article.approver %>
            <% end %>
        <% end %>
        <% if @article.updated? %>
            <br />
            Last update <%= @article.updated_at.to_date.inspect %>
        <% end %>
    </span>
    <% if this_user&.can_edit? @article %>
        <%= render 'actions', article: @article, cached: true %>
    <% end %>
</div>
<hr />

<div class="markdown-content">
    <%== @article.rendered %>
</div>