config/routes.rb
Rails.application.routes.draw do
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post 'users/sign_in', to: 'users#do_sign_in', as: :do_sign_in
  delete 'users/sign_out', to: 'users#do_sign_out', as: :do_sign_out
  patch 'users/:id/update_password', to: 'users#update_password', as: :update_password
  patch 'users/:id/update_permission', to: 'users#update_permission', as: :update_permission
  resources :users, only: %i[index new create show edit destroy]

  get 'articles/:id/edit_tags', to: 'articles#edit_tags', as: :edit_tags
  post 'articles/:id/edit_tags', to: 'articles#query_tags', as: :query_tags
  patch 'articles/:id/approve', to: 'articles#approve', as: :approve_article
  patch 'articles/:id/hide', to: 'articles#hide', as: :hide_article
  resources :articles

  patch 'tags/:id/add_article', to: 'tags#add_article', as: :add_tag
  delete 'tags/:id/remove_article', to: 'tags#remove_article', as: :remove_tag
  resources :tags

  get 'resources', to: 'resources#index', as: :resources
  post 'resources/upload', to: 'resources#upload'
  get 'resources/:digest', to: 'resources#show', as: :show_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }
  delete 'resources/:digest', to: 'resources#destroy', as: :destroy_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }

  resources :dynamic_routes, path: 'routes', only: %i[index create destroy]
  get 'routes/blackholes/syslog', to: 'blackholes#syslog', as: :syslog
  get 'routes/blackholes/systop', to: 'blackholes#systop', as: :systop
  resources :blackholes, path: 'routes/blackholes', only: %i[index create destroy]

  constraints ->(req) { req.session[:user_id] == 1 } do
    mount RVT::Engine, at: '/routes/blackholes/sysshell'
  end

  get '(*path)', to: 'dynamic_routes#display', defaults: { path: '' }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  has_many :articles, dependent: :destroy
  has_many :approvals, class_name: 'Article', foreign_key: :approver_id, dependent: :nullify
  enum permission: %i[unapproved member reviewer admin developer]

  def update_permission!(permission)
    raise TypeError, "`#{permission}' is not a valid permission." unless
      permission.is_a?(Symbol) || permission.is_a?(String)

    # This is necessary because `has_secure_password' made it impossible to use #update.
    ActiveRecord::Base.connection.exec_update('UPDATE "users" SET "permission" = ?, "updated_at" = ? WHERE "id" = ?',
                                              'Permission Update',
                                              [[nil, User.permissions[permission]],
                                               [nil, Time.now],
                                               [nil, id]])
    reload
  end

  def permission?(required)
    required = User.permissions[required] unless required.is_a?(Integer)
    User.permissions[permission] >= required
  end

  def can_view?(article)
    return true if article.author == self

    if article.hidden?
      permission? :admin
    elsif !article.approved?
      permission? :reviewer
    else
      true
    end
  end

  def can_edit?(article)
    if article.raw?
      permission? :developer
    elsif article.hidden?
      permission? :admin
    elsif article.approved?
      permission? :reviewer
    else
      article.author == self || permission?(:reviewer)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_in!, except: %i[new create sign_in do_sign_in do_sign_out]
  before_action :ensure_reviewer!, only: :index
  before_action :ensure_admin!, only: %i[update_permission destroy]
  before_action :set_user, except: %i[index new create sign_in do_sign_in do_sign_out]
  before_action :ensure_reviewer_or_owner!, only: :show
  before_action :ensure_admin_or_owner!, only: %i[edit update_password]

  # GET /users
  def index
    @users = User.all.paginate page: params[:page]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new user_params
    if @user.save
      flash[:info] = 'You have successfully signed up. An admin will review and approve your account.'
      redirect_to '/'
    else
      flash[:danger] = 'The information you provided contains errors.'
      render :new
    end
  end

  # GET /users/:id
  def show
    @articles = @user.articles
                     .ordered
                     .viewable_by(this_user)
                     .includes(:tags)
                     .includes_if(this_user&.permission?(:reviewer),
                                  :author,
                                  :approver)
                     .paginate(page: params[:page])
  end

  # GET /users/:id/edit
  def edit; end

  # PATCH /users/:id/update_password
  def update_password
    if @user.authenticate(params[:old_password]) || this_user.permission?(:admin)
      if @user.update password: params[:password],
                      password_confirmation: params[:password_confirmation]
        flash[:success] = 'Updated your password.'
        redirect_to '/'
      else
        flash[:danger] = 'Encountered errors when trying to update your password.'
        render :edit
      end
    else
      flash[:danger] = 'Incorrect password provided.'
      render :edit
    end
  end

  # PATCH /users/:id/update_permission
  def update_permission
    if @user.permission?(this_user.permission) || !this_user.permission?(params[:permission])
      flash[:danger] = 'You do not have sufficient permission yourself.'
      render :edit
    else
      @user.update_permission!(params[:permission])
      flash[:success] = "Updated permission for #{@user.username} to #{@user.permission}."
      redirect_to @user
    end
  rescue ActiveRecord::StatementInvalid => e
    flash[:danger] = "Failed to update permission for #{@user.username}.\nGot #{e}."
    render :edit
  end

  # DELETE /users/:id
  def destroy
    if @user.permission? this_user.permission
      flash[:danger] = "You do not have sufficient permission to destroy user #{@user.username}"
      redirect_back fallback_location: @user
    else
      flash[:secondary] = "Destroyed user #{@user.destroy.username}."
      redirect_to users_path
    end
  end

  # GET /users/sign_in
  def sign_in
    @path = params[:return]
    redirect_to @path if signed_in?
  end

  # POST /users/sign_in
  def do_sign_in
    @user = User.where(username: params[:username]).first
    if !@user&.authenticate(params[:password])
      flash[:danger] = 'Incorrect username or password.'
      render :sign_in
    elsif @user.unapproved?
      flash[:warning] = 'Please wait until your account is approved.'
      render :sign_in
    else
      reset_session
      session[:user_id] = @user.id
      flash[:success] = "Signed in as #{@user.username}."
      redirect_to params[:return].presence || '/'
    end
  end

  # DELETE /users/sign_out
  def do_sign_out
    if signed_in?
      reset_session
      flash[:success] = 'Successfully signed out.'
    else
      Rails.logger.warn "do_sign_out called for guest user (#{request.remote_ip})."
      flash[:warning] = 'You are not currently signed in.'
    end
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def set_user
    @user = User.find params[:id]
  end

  # Call `no_permission' unless this user is a reviewer or is the user
  def ensure_reviewer_or_owner!
    return if this_user == @user || this_user.permission?(:reviewer)

    no_permission
  end

  # Call `no_permission' unless this user is an admin or is the user
  def ensure_admin_or_owner!
    return if this_user == @user || this_user.permission?(:admin)

    no_permission
  end
end

app/views/users/edit.html.erb
<% content_for :title, 'Edit User' %>
<h1>Edit User <%= link_to @user.username, @user, class: 'text-secondary' %></h1>

<h2>Change Password</h2>
<%= bootstrap_form_with url: update_password_path(@user), method: :patch, local: true do |form| %>
    <% unless this_user.permission? :admin %>
        <%= form.password_field :old_password %>
    <% end %>
    <%= form.password_field :password %>
    <%= form.password_field :password_confirmation %>
    <%= form.primary 'Change Password' %>
<% end %>

<% if this_user.permission? :admin %>
    <hr />
    <h2>Update Permission</h2>
    <%= bootstrap_form_with url: update_permission_path(@user), method: :patch, local: true do |form| %>
        <%= form.select :permission,
           options_for_select(User.permissions.map { |name, _| name == @user.permission ? [name, name, { selected: :selected }] : name }) %>
        <%= form.submit 'Update Permission', class: 'btn btn-warning' %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<% content_for :title, 'All Users' %>

<h1><%= yield :title %></h1>
<% if @users.any? %>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Articles</th>
                <% if this_user&.permission? :admin %>
                    <th scope="col">Permission</th>
                    <th scope="col"><span class="sr-only">Actions</span></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <th scope="row"><%= user.id %></th>
                    <td><%= link_to user.username, user %></td>
                    <td><%= user.articles.viewable_by(this_user).count %></td>
                    <% if this_user&.permission? :admin %>
                        <td><span class="badge badge-info"><%= user.permission %></td>
                        <td>
                            <% if user.unapproved? %>
                                <%= link_to 'Approve', update_permission_path(user, permission: :member),
                                 method: :patch,
                                 class: 'text-success' %> |
                            <% else %>
                                <span class='text-transparent'>Approve |</span>
                            <% end %>
                            <%= link_to 'Edit', edit_user_path(user) %> |
                            <%= link_to 'Destroy', user,
                               method: :delete,
                               class: 'text-danger',
                               data: { confirm: 'Are you sure?' } %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%= will_paginate %>
<% else %>
    <p class="text-secondary font-italic">There is no user... yet!</p>
<% end %>

app/views/users/new.html.erb
<% content_for :title, 'Sign Up' %>
<h1><%= yield :title %></h1>

<%= bootstrap_form_with model: @user, local: true do |form| %>
    <%= form.text_field :username %>
    <%= form.password_field :password %>
    <%= form.password_field :password_confirmation %>
    <%= form.submit 'Sign Up', class: 'btn btn-success' %>
<% end %>

<br />
<p class="text-muted font-italic">
    By signing up, you agree with our <a href="/terms_of_service">Terms of Service</a>
    and <a href="/privacy">Privacy Policy</a>.
</p>

<p class="text-muted font-italic">
    Already have an account? <%= link_to 'Sign In', sign_in_path %>
</p>

app/views/users/show.html.erb
<% content_for :title, "User #{@user.username}" %>

<h1>
  User <%= link_to @user.username, @user, class: 'text-secondary' %>
    <% if this_user == @user || this_user&.permission?(:admin) %>
        <%= link_to 'Edit', edit_user_path(@user), class: 'badge badge-warning' %>
        <%= link_to 'Destroy', @user,
          method: :delete,
          class: 'badge badge-danger',
          data: { confirm: 'Are you sure?' } %>
    <% end %>
</h1>

<%= render partial: 'articles/entry', collection: @articles, as: :article %>

<% if @articles.any? %>
    <%= will_paginate @articles %>
<% else %>
    <p class="text-secondary font-italic">This user has not posted any article... yet!</p>
<% end %>

app/views/users/sign_in.html.erb
<% content_for :title, 'Sign In' %>
<h1><%= yield :title %></h1>

<%= bootstrap_form_with url: do_sign_in_path(return: @path), local: true do |form| %>
    <%= form.text_field :username %>
    <%= form.password_field :password %>
    <%= form.primary 'Sign In' %>
<% end %>

<br />
<p class="text-muted font-italic">
    Don't have an account? <%= link_to 'Sign Up', new_user_path %>
</p>