config/routes.rb
Rails.application.routes.draw do
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post 'users/sign_in', to: 'users#do_sign_in', as: :do_sign_in
  delete 'users/sign_out', to: 'users#do_sign_out', as: :do_sign_out
  patch 'users/:id/update_password', to: 'users#update_password', as: :update_password
  patch 'users/:id/update_permission', to: 'users#update_permission', as: :update_permission
  resources :users, only: %i[index new create show edit destroy]

  get 'articles/:id/edit_tags', to: 'articles#edit_tags', as: :edit_tags
  post 'articles/:id/edit_tags', to: 'articles#query_tags', as: :query_tags
  patch 'articles/:id/approve', to: 'articles#approve', as: :approve_article
  patch 'articles/:id/hide', to: 'articles#hide', as: :hide_article
  resources :articles

  patch 'tags/:id/add_article', to: 'tags#add_article', as: :add_tag
  delete 'tags/:id/remove_article', to: 'tags#remove_article', as: :remove_tag
  resources :tags

  get 'resources', to: 'resources#index', as: :resources
  post 'resources/upload', to: 'resources#upload'
  get 'resources/:digest', to: 'resources#show', as: :show_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }
  delete 'resources/:digest', to: 'resources#destroy', as: :destroy_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }

  resources :dynamic_routes, path: 'routes', only: %i[index create destroy]
  get 'routes/blackholes/syslog', to: 'blackholes#syslog', as: :syslog
  get 'routes/blackholes/systop', to: 'blackholes#systop', as: :systop
  resources :blackholes, path: 'routes/blackholes', only: %i[index create destroy]

  constraints ->(req) { req.session[:user_id] == 1 } do
    mount RVT::Engine, at: '/routes/blackholes/sysshell'
  end

  get '(*path)', to: 'dynamic_routes#display', defaults: { path: '' }
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :articles

  before_validation :substitute_whitespace

  scope :ordered, -> { order(id: :asc) }

  private

  def substitute_whitespace
    name&.downcase!
    name&.gsub!(/\s+/, '-')
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :ensure_signed_in!, except: %i[index show]
  before_action :set_tag, except: %i[index new create]
  before_action :set_article, only: %i[add_article remove_article]
  before_action :ensure_edit_permission!, only: %i[add_article remove_article]

  # GET /tags
  def index
    @tags = Tag.all.paginate page: params[:page]
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # POST /tags
  def create
    @tag = if params[:query].present?
             Tag.new name: params[:query]
           else
             Tag.new tag_params
           end

    if @tag.save
      flash[:success] = "Created tag ##{@tag.name}."
      if params[:query].present?
        redirect_back fallback_location: @tag
      else
        redirect_to @tag
      end
    else
      flash[:danger] = 'Errors encountered when creating the tag.'
      render :new
    end
  end

  # GET /tags/:id
  def show
    fresh_when @tag

    @articles = @tag.articles
                    .ordered
                    .viewable_by(this_user)
                    .includes(:tags)
                    .includes_if(this_user&.permission?(:reviewer),
                                 :author,
                                 :approver)
                    .paginate(page: params[:page])
  end

  # GET /tags/:id/edit
  def edit; end

  # PATCH /tags/:id
  def update
    if @tag.update tag_params
      flash[:success] = 'Updated the tag.'
      redirect_to @tag
    else
      flash[:error] = 'Failed to update the tag.'
      render :edit
    end
  end

  # DELETE /tags/:id
  def destroy
    flash[:secondary] = "Deleted tag ##{@tag.destroy.name}."
    redirect_to tags_path
  end

  # PATCH /tags/:id/add_article
  def add_article
    if @tag.articles.include? @article
      flash[:warning] = "The article already has tag ##{@tag.name}."
    else
      @tag.articles << @article
      flash[:success] = "Added tag ##{@tag.name} to article \"#{@article.title}\"."
    end
    redirect_back fallback_location: edit_tags_path(@article)
  end

  # PATCH /tags/:id/remove_article
  def remove_article
    if @tag.articles.include? @article
      @tag.articles.delete @article
      flash[:secondary] = "Removed tag ##{@tag.name} from article \"#{@article.title}\"."
    else
      flash[:warning] = "The article does not have tag ##{@tag.name}."
    end
    redirect_back fallback_location: edit_tags_path(@article)
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :description)
  end

  def set_tag
    @tag = Tag.find params[:id]
  end

  def set_article
    @article = Article.find params[:article_id]
  end

  def ensure_edit_permission!
    return if this_user.can_edit? @article

    no_permission
  end
end

app/views/tags/_form.html.erb
<%= bootstrap_form_with model: @tag, local: true do |form| %>
    <%= form.text_field :name, prepend: '#' %>
    <%= form.text_area :description %>
    <%= form.submit 'Save' %>
<% end %>

app/views/tags/_tag.html.erb
<% if tag.description.present? %>
    <%= link_to "##{tag.name}", tag, class: 'badge badge-success',
     title: tag.description, data: { toggle: 'tooltip' } %>
<% else %>
    <%= link_to "##{tag.name}", tag, class: 'badge badge-success' %>
<% end %>

app/views/tags/edit.html.erb
<% content_for :title, 'Edit Tag' %>
<h1>Edit <%= render 'tag', tag: @tag, cached: true %></h1>

<%= render 'form' %>

app/views/tags/index.html.erb
<% content_for :title, 'All Tags' %>

<h1><%= yield :title %></h1>

<% if @tags.any? %>
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <% if signed_in? %>
                  <th scope="col"><span class="sr-only">Actions</span></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @tags.each do |tag| %>
                <tr>
                    <th scope="row"><%= tag.id %></th>
                    <td><%= render 'tag', tag: tag, cached: true %></td>
                    <td>
                        <% if tag.description.blank? %>
                            <span class="text-muted font-italic">
                                There is no description for this tag... yet!
                            </span>
                        <% else %>
                            <span class="text-secondary">
                                <%= tag.description.truncate(64).gsub(/\n+/, ' ') %>
                            </span>
                        <% end %>
                    </td>
                    <% if signed_in? %>
                        <td>
                            <%= link_to 'Edit', edit_tag_path(tag) %> |
                            <%= link_to 'Delete', tag,
                               method: :delete,
                               class: 'text-danger',
                               data: { confirm: 'Are you sure?' } %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%= will_paginate %>
<% else %>
    <p class="text-secondary font-italic">
        There is no tag... yet!
        <% if signed_in? %>
            <%= link_to 'New Tag', new_tag_path %>
        <% end %>
    </p>
<% end %>

app/views/tags/new.html.erb
<% content_for :title, 'New Tag' %>
<h1><%= yield :title %></h1>

<%= render 'form' %>

app/views/tags/show.html.erb
<% content_for :title, "Tag ##{@tag.name}" %>

<h1>Tag <%= render 'tag', tag: @tag, cached: true %></h1>
<% if @tag.description.blank? %>
    <p class="text-muted font-italic">There is no description for this tag... yet!</p>
<% else %>
    <p class="text-secondary"><%= @tag.description %></p>
<% end %>
<% if signed_in? %>
    <%= link_to 'Edit', edit_tag_path(@tag) %> |
    <%= link_to 'Delete', tag_path(@tag),
       method: :delete,
       class: 'text-danger',
       data: { confirm: 'Are you sure?' } %>
<% end %>
<hr />

<%= render partial: 'articles/entry', collection: @articles, as: :article %>

<% if @articles.any? %>
    <%= will_paginate @articles %>
<% else %>
    <p class="text-secondary font-italic">There is no article with this tag... yet!</p>
<% end %>