config/routes.rb
Rails.application.routes.draw do
  get 'users/sign_in', to: 'users#sign_in', as: :sign_in
  post 'users/sign_in', to: 'users#do_sign_in', as: :do_sign_in
  delete 'users/sign_out', to: 'users#do_sign_out', as: :do_sign_out
  patch 'users/:id/update_password', to: 'users#update_password', as: :update_password
  patch 'users/:id/update_permission', to: 'users#update_permission', as: :update_permission
  resources :users, only: %i[index new create show edit destroy]

  get 'articles/:id/edit_tags', to: 'articles#edit_tags', as: :edit_tags
  post 'articles/:id/edit_tags', to: 'articles#query_tags', as: :query_tags
  patch 'articles/:id/approve', to: 'articles#approve', as: :approve_article
  patch 'articles/:id/hide', to: 'articles#hide', as: :hide_article
  resources :articles

  patch 'tags/:id/add_article', to: 'tags#add_article', as: :add_tag
  delete 'tags/:id/remove_article', to: 'tags#remove_article', as: :remove_tag
  resources :tags

  get 'resources', to: 'resources#index', as: :resources
  post 'resources/upload', to: 'resources#upload'
  get 'resources/:digest', to: 'resources#show', as: :show_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }
  delete 'resources/:digest', to: 'resources#destroy', as: :destroy_resource, constraints: { digest: /[A-Fa-f0-9]{64}/ }

  resources :dynamic_routes, path: 'routes', only: %i[index create destroy]
  get 'routes/blackholes/syslog', to: 'blackholes#syslog', as: :syslog
  get 'routes/blackholes/systop', to: 'blackholes#systop', as: :systop
  resources :blackholes, path: 'routes/blackholes', only: %i[index create destroy]

  constraints ->(req) { req.session[:user_id] == 1 } do
    mount RVT::Engine, at: '/routes/blackholes/sysshell'
  end

  get '(*path)', to: 'dynamic_routes#display', defaults: { path: '' }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>
            <% if content_for? :title %>
                <%= yield :title %> -
            <% end %>
            ULead Association
        </title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no" />
        <%= favicon_pack_tag 'media/img/ulead_logo.png' %>
        <script src="https://cdn.jsdelivr.net/npm/turbolinks@5/dist/turbolinks.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js" defer="defer"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4/dist/js/bootstrap.bundle.min.js" defer="defer"></script>
        <script src="https://cdn.jsdelivr.net/npm/@rails/ujs@6/lib/assets/compiled/rails-ujs.min.js" defer="defer"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4/dist/css/bootstrap.min.css" />
        <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', nonce: true, defer: true %>
        <% if content_for? :header %>
            <%= yield :header %>
        <% end %>
    </head>

    <body class="bg-light">
        <nav class="navbar navbar-dark navbar-expand-md sticky-top" style="background-color: #BB8800">
            <a class="navbar-brand" href="/">
                <%= image_pack_tag 'media/img/ulead_logo.png', width: 40, height: 40, alt: 'ULead Logo' %>
                <strong>ULead</strong>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-content">
                <span class="sr-only">Toggle Navbar</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbar-collapse-content" class="collapse navbar-collapse justify-content-between">
                <ul class="navbar-nav">
                    <%= nav_link 'Blog', articles_path %>
                    <%= nav_link 'Tags', tags_path %>
                    <%= nav_link 'About', '/about_us' %>
                    <% if signed_in? %>
                        <%= nav_link 'New Article', new_article_path %>
                        <%= nav_link 'New Tag', new_tag_path %>
                    <% end %>
                    <% if this_user&.permission? :reviewer %>
                        <%= nav_link 'Users', users_path %>
                    <% end %>
                    <% if this_user&.permission? :developer %>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                                Developer
                            </a>
                            <ul class="dropdown-menu">
                                <li><%= link_to 'Resources', resources_path, class: 'dropdown-item' %></li>
                                <li><%= link_to 'Routes', dynamic_routes_path, class: 'dropdown-item' %></li>
                                <li><%= link_to 'Blackholes', blackholes_path, class: 'dropdown-item' %></li>
                                <li><%= link_to 'Production Logs', syslog_path, class: 'dropdown-item' %></li>
                                <li><%= link_to 'OS Status', systop_path, class: 'dropdown-item' %></li>
                            </ul>
                        </li>
                    <% end %>
                </ul>
                <ul class="navbar-nav">
                    <% if signed_in? %>
                        <%= nav_link this_user.username, this_user %>
                        <%= nav_link 'Sign Out', do_sign_out_path, method: :delete %>
                    <% else %>
                        <%= nav_link 'Join Us', '/join_us' %>
                        <%= nav_link 'Sign In', sign_in_path(return: request.path) %>
                    <% end %>
                </ul>
            </div>
        </nav>

        <div class="container mt-3">
            <% flash.each do |type, msg| %>
                <div class="alert alert-dismissible alert-<%= css_alert?(type) ? type : 'info' %>">
                    <span class="sr-only"><strong><%= type %>: </strong></span>
                    <%= msg %>
                </div>
            <% end %>
        </div>
        <% flash.clear %>

        <div class="container main-content mt-3">
            <%= yield %>
        </div>

        <footer class="text-center">
            <br />
            <p class="text-muted">
                ULead Association - Uniting Young People Passionate About Social Initiatives
            </p>
        </footer>
    </body>
</html>